---
- name: Create Redis
  hosts: all
  become: yes
  tasks:
    - name: Create redis_data directory
      file:
        path: /home/code/redis_data
        state: directory

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.redis.yaml.j2
        dest: /home/code/docker-compose.redis.yaml

    - name: Run Redis service
      shell: docker stack deploy --compose-file=/home/code/docker-compose.redis.yaml redis
