---
- name: Delete host
  hosts: all
  become: yes
  vars:
    service_name: "{{ SERVICE_NAME }}"
  tasks:
    - name: Remove host stack
      shell: docker stack rm {{ service_name }}
      register: result
      failed_when: result.rc != 0
      ignore_errors: false

    - name: Debug result of removing host stack
      debug:
        var: result

    - name: Ensure host stack is removed
      shell: docker stack ls | grep {{ service_name }}
      register: check_host
      failed_when: check_host.rc == 0
      ignore_errors: true

    - name: Delete env file
      file:
        path: "/home/code/{{ service_name }}.env.local"
        state: absent

    - name: Delete docker-compose file
      file:
        path: /home/code/docker-compose.host.yaml
        state: absent

    - name: Delete webhook info file
      file:
        path: /home/code/host_webhook.json
        state: absent

    - name: Delete webhook token file
      file:
        path: /home/code/host_webhook_token
        state: absent
