---
- name: Delete host
  hosts: all
  become: yes
  vars:
    - service_name: "{{ SERVICE_NAME }}"
  tasks:
    - name: Remove host service
      shell: docker compose -f /home/code/docker-compose.host.yaml down

    - name: Delete docker-compose file
      file:
        path: /home/code/docker-compose.host.yaml
        state: absent

    - name: Delete webhook info file
      file:
        path: /home/code/host_webhook.json
        state: absent

    - name: Delete webhook token file
      file:
        path: /home/code/host_webhook_token
        state: absent
