image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    name: Frontend
    visibility: public
  - port: 8080
    name: Adminer
    visibility: public

tasks:
  - name: "bash"
    init: npm i
  - name: "infrastructure"
    init: ./apps/db/up.sh && ./apps/redis/up.sh

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - esbenp.prettier-vscode
    - github.vscode-github-actions
    - ms-playwright.playwright
    - bradlc.vscode-tailwindcss
    - nrwl.angular-console
    - firsttris.vscode-jest-runner
    - eamodio.gitlens
