image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    name: Frontend
    visibility: public
  - port: 8080
    name: Adminer
    visibility: public

tasks:
  - name: "install dependencies"
    init: bun i
  - name: "db"
    init: cd apps/db && ./up.sh
    command: npx nx run frontend:db:seed
  - name: "app"
    init: cd frontend && npm i

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - dsznajder.es7-react-js-snippets
    - dbaeumer.vscode-eslint
    - mhutchie.git-graph
    - esbenp.prettier-vscode
    - chakrounanas.turbo-console-log
    - hbenl.vscode-test-explorer
    - GitHub.copilot
    - bradlc.vscode-tailwindcss
    - nrwl.angular-console
