version: "3.7"

services:
  db:
    extends:
      file: ./apps/db/docker-compose.postgres.yaml
      service: postgres
    networks:
      - sps_db_network

  redix:
    extends:
      file: ./apps/redis/docker-compose.redis.yaml
      service: redis
    networks:
      - sps_db_network

  frontend:
    extends:
      file: ./apps/frontend/docker-compose.frontend.yaml
      service: frontend
    networks:
      - sps_db_network
    ports:
      - 3000:3000

networks:
  sps_db_network:
    external: false
    name: sps_db_network
