version: "3.7"

services:
  db:
    extends:
      file: ./apps/db/docker-compose.postgres.yaml
      service: postgres
    networks:
      - overlay_network

  redis:
    extends:
      file: ./apps/redis/docker-compose.redis.yaml
      service: redis
    networks:
      - overlay_network

  host:
    image: "host"
    env_file:
      - ./apps/host/.env.local
    command: "sh -c './start.sh host'"
    ports:
      - "3000:3000"
    networks:
      - overlay_network

networks:
  overlay_network:
    external: false
    name: ${COMPOSE_PROJECT_NAME}_overlay_network
