version: "3.7"

services:
  db:
    extends:
      file: ./apps/db/docker-compose.postgres.yaml
      service: postgres
    networks:
      - overlay_network

  redis:
    extends:
      file: ./apps/redis/docker-compose.redis.yaml
      service: redis
    networks:
      - overlay_network

  host:
    # image: "singlepagestartup/singlepagestartup:0.0.157"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./apps/host/.env.local
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - KV_PROVIDER=redis
      - KV_PORT=6379
    command: "sh -c './start.sh host'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - overlay_network

networks:
  overlay_network:
    external: false
    name: ${COMPOSE_PROJECT_NAME}_overlay_network
