version: "3.7"

services:
  db:
    extends:
      file: ./apps/db/docker-compose.postgres.yaml
      service: postgres
    networks:
      - sps_db_network

  redis:
    extends:
      file: ./apps/redis/docker-compose.redis.yaml
      service: redis
    networks:
      - sps_db_network

networks:
  sps_db_network:
    external: false
    name: sps_db_network
