---
- name: Delete Traefik
  hosts: all
  become: yes
  tasks:
    - name: Remove Traefik service
      shell: docker compose -f /home/code/docker-compose.traefik.yaml down

    - name: Delete traefik.yml file
      file:
        path: /home/code/traefik.yml
        state: absent

    - name: Delete docker-compose file
      file:
        path: /home/code/docker-compose.traefik.yaml
        state: absent
