---
- name: Init Docker Swarm
  hosts: all
  become: yes
  tasks:
    - name: Check is Docker swarm already started
      shell: docker info | grep -E -i "Swarm[\s]*:.*active" | awk '{print $2}'
      register: docker_swarm_mode
      failed_when: false
      changed_when: false

    - name: Init Docker swarm
      shell: docker swarm init --advertise-addr "{{ ansible_default_ipv4.address }}"
      when: docker_swarm_mode.stdout == "inactive"

    - name: Join Docker swarm as manager
      shell: docker swarm join-token manager
      when: docker_swarm_mode.stdout == "inactive"
