- name: Set cron jobs
  hosts: all
  become: yes
  vars:
    api_service_url: "{{ API_SERVICE_URL }}"
    rbac_secret_key: "{{ RBAC_SECRET_KEY }}"
    database_backup_retention_days: "{{ DATABASE_BACKUP_RETENTION_DAYS | default('14', true) }}"
  tasks:
    - name: docker image prune cron
      cron:
        name: "docker image prune"
        minute: "*/5"
        job: "yes | docker image prune  >> /home/code/docker_image_prune.log"

    - name: docker container prune cron
      cron:
        name: "docker container prune"
        minute: "*/5"
        job: "yes | docker container prune  >> /home/code/docker_container_prune.log"

    - name: Create postgres dump directory
      file:
        path: /home/code/db_backups
        state: directory
        mode: "0700"

    - name: create postgres dump
      cron:
        name: "create postgres dump"
        minute: "0"
        hour: "0"
        job: "DATABASE_BACKUP_RETENTION_DAYS={{ database_backup_retention_days }} /home/code/create_db_dump.sh >> /home/code/create_db_dump.log 2>&1"
