version: "3.7"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./create_application_role.sh:/docker-entrypoint-initdb.d/create_application_role.sh:ro
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
