version: "3.7"

services:
  db:
    extends:
      file: ./docker-compose.postgres.yaml
      service: postgres
    env_file:
      - ./.env
    networks:
      - db_network

  adminer:
    extends:
      file: ./docker-compose.adminer.yaml
      service: adminer
    env_file:
      - ./.env
    networks:
      - db_network

networks:
  db_network:
    external: false
    name: ${COMPOSE_PROJECT_NAME}_db_network
