---
- name: Create telegram
  hosts: all
  become: yes
  vars:
    service_name: "{{ SERVICE_NAME }}"
    portainer_username: "{{ PORTAINER_USERNAME }}"
    portainer_password: "{{ PORTAINER_PASSWORD }}"
    portainer_url: "{{ PORTAINER_URL }}"
  tasks:
    - name: Copy set-portainer-webhook.js
      copy:
        src: ../portainer/set-portainer-webhook.js
        dest: /home/code/set-portainer-webhook.js

    - name: Get registry_id from file
      shell: cat /home/code/docker_hub_registry_id
      register: cmd_docker_hub_registry_id

    - name: Create telegram.env file
      ansible.builtin.template:
        src: telegram.env.j2
        dest: /home/code/telegram.env

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.telegram.yaml.j2
        dest: /home/code/docker-compose.telegram.yaml

    - name: Run telegram service
      shell: docker stack deploy --with-registry-auth --compose-file=/home/code/docker-compose.telegram.yaml telegram

    - name: Get api service id
      shell:
        cmd: "docker service ls -f name=telegram_telegram -q"
      register: cmd_telegram_service_id

    - name: Run set-portainer-webhook.js
      shell:
        cmd: node /home/code/set-portainer-webhook.js "{{ cmd_telegram_service_id.stdout_lines[0] }}" "{{ cmd_docker_hub_registry_id.stdout }}" "{{ portainer_url }}" "{{ portainer_username }}" "{{ portainer_password }}" "telegram_webhook"
      register: cmd_set_telegram_webhook

    # - debug:
    #     msg: "{{ cmd_set_api_webhook }}"

    - name: Copy webhook info file
      fetch:
        src: /home/code/telegram_webhook.json
        dest: "./"
        flat: yes

    - name: Delete artifacts
      file:
        path: "/home/code/{{ item }}"
        state: absent
      loop:
        - "set-portainer-webhook.js"
