---
- name: Create GitHub Secret
  hosts: all
  become: yes
  vars:
    - github_token: "{{ GITHUB_TOKEN }}"
    - github_repository: "{{ GITHUB_REPOSITORY }}"
    - secret_name: "{{ SECRET_NAME }}"
    - secret_content: "{{ SECRET_CONTENT }}"
    - secret_scope: "{{ SECRET_SCOPE | default('actions') }}"
  tasks:
    - name: Create github-node-api directory
      file:
        path: "/home/code/github-node-api"
        state: directory

    - name: Fill github-node-api directory from local
      copy:
        src: "{{ playbook_dir }}/github-node-api/{{ item }}"
        dest: "/home/code/github-node-api/{{ item }}"
      loop:
        - create_secret.js
        - package.json

    - name: Install dependencies
      shell:
        cmd: "npm install"
        chdir: "/home/code/github-node-api"

    - name: Set secrets to GitHub
      no_log: true
      shell:
        cmd: "node ./create_secret.js {{ github_token }} {{ github_repository }} {{ secret_name }} {{ secret_content }} {{ secret_scope }}"
        chdir: "/home/code/github-node-api"

    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent
