import { ContentfulStatusCode } from "hono/utils/http-status";

// Все паттерны — только RegExp, шаблонные и строковые убраны
export const httpErrorPatterns = new Map<ContentfulStatusCode, RegExp[]>([
  [
    400,
    [
      /no refresh token provided/i,
      /invalid request body/i,
      /rbac_jwt_secret not set/i,
      /rbac_secret_key not set/i,
      /invalid token issued/i,
      /validation error/i,
      /no id provided/i,
      /invalid url/i,
      /telegram bot is not running/i,
      /rbac_secret_key is not defined/i,
      /rbac_anonymous_jwt_refresh_token_lifetime_in_seconds not set/i,
      /rbac secret key not found/i,
      /environment error[.,]? rbac_secret_key not found/i,
      /invalid id([.,]|, id is required)?/i,
      /payment intent not found/i,
      /currency (is required|not found)/i,
      /not found entity with id/i,
      /query (segment|url) is required/i,
      /invalid ordertoproductid/i,
      /invalid messageid([.,]|, messageid is required)?/i,
      /invalid (data|body)/i,
      /invalid data, (slug and payload|data) are required([.]|.)?/i,
      /invalid data, should be array/i,
      /invalid notification method/i,
      /no uuid provided/i,
      /no notification[.]?notification[.]?method provided/i,
      /no notification[.]?topic[.]?slug provided/i,
      /no template variant provided/i,
      /files are not supported/i,
      /missing headers/i,
      /provider .* is not allowed/i,
      /email is required/i,
      /payment intents to invoices not found/i,
      /cloudpayments (credentials|invoice id) not found/i,
      /channel not found/i,
      /stripe secret key not found/i,
      /orders to billing module payment intents not found/i,
      /payment intents not found/i,
      /payment intent is not succeeded/i,
      /invalid file (type)?/i,
      /invalid (message|signature)/i,
      /multiple subjects to identities found/i,
      /cannot delete last identity/i,
      /account already exists/i,
      /invalid date in message/i,
      /multiple files are not allowed/i,
      /missing one or more action parameters \(route, method, type\)/i,
      /multiple identities found/i,
      /could not update identity/i,
      /no salt found for this identity/i,
      /passwords do not match/i,
      /no password provided/i,
      /code is expired[.]? resend again[.]?/i,
      /no code provided/i,
      /no method provided in 'action' query/i,
      /no route provided in 'action' query/i,
      /no action provided in query/i,
      /configuration error[.]?/i,
      /no data[.]?formid provided/i,
      /no productid provided/i,
      /multiple billing module payment/i,
      /invalid provider/i,
      /invalid ordertoproductid[.]? got/i,
      /invalid id[.]? got:?/i,
    ],
  ],
  [
    401,
    [
      /invalid credentials/i,
      /unauthorized/i,
      /token required/i,
      /no session/i,
      /authorization error/i,
      /no subject provided in the token/i,
    ],
  ],
  [
    403,
    [
      /forbidden/i,
      /authentication/i,
      /permission/i,
      /unauthorized/i,
      /only order owner can update order/i,
      /only identity owner can create identity/i,
    ],
  ],
  [
    404,
    [
      /not found/i,
      /not found[.]? entity with id/i,
      /form not found/i,
      /entity not found/i,
      /entity with param .* not found/i,
      /no inputs found/i,
      /order already exists/i,
      /no topic found/i,
      /no form found/i,
      /no ecommerce(module)?( orders)?( products)?( attributes)?(?:.*) provided/i,
      /no data[.]?productid provided/i,
      /no ecommerce(module)?\.orders\[number\]\.id provided/i,
      /multiple stores found[.]? pass 'data\.storeid/i,
      /no email provided/i,
      /no stores found/i,
      /no inputs found for form with id/i,
      /no orderid provided/i,
      /no orders(toproducts)? provided/i,
      /order is not in 'new' status/i,
      /no template found/i,
      /order not found/i,
      /order to product not found/i,
      /orders to products not found/i,
      /no orders to products found/i,
      /no attributes (found|keys to attributes found)/i,
      /products not found/i,
      /billing currencies not found/i,
      /orders to billing module currencies not found/i,
      /billing module currencies not found/i,
      /no subjects to identities found/i,
      /no identities found/i,
      /no products to attributes found/i,
      /no attribute keys to attributes found/i,
      /no order found/i,
      /no entity found/i,
      /no payment intents found/i,
      /no payment intents to invoices found/i,
      /no invoices found/i,
      /no updated order found/i,
      /not found[.]? no matching action for route:?/i,
      /no ecommerce orders to billing module currencies found/i,
      /no billing module currency id found for order:?/i,
    ],
  ],
  [
    422,
    [
      /expected string/i,
      /invalid body\['data'\]/i,
      /unprocessable entity/i,
      /invalid type[.]? expected email, got:?/i,
    ],
  ],
  [
    500,
    [
      /configuration error/i,
      /internal server error/i,
      /request not created/i,
      /jwt secret not provided/i,
      /server error/i,
    ],
  ],
]);
