import { ContentfulStatusCode } from "hono/utils/http-status";

export const httpErrorPatterns = new Map<
  ContentfulStatusCode,
  (string | RegExp)[]
>([
  [
    400,
    [
      "No refresh token provided",
      "Invalid request body",
      "RBAC_JWT_SECRET not set",
      "RBAC_SECRET_KEY not set",
      "Invalid token issued",
      "Validation error",
      "No id provided",
      "Invalid url",
      "Telegram bot is not running",
      "RBAC_SECRET_KEY not set",
      "RBAC_SECRET_KEY is not defined",
      "RBAC_ANONYMOUS_JWT_REFRESH_TOKEN_LIFETIME_IN_SECONDS not set",
      "RBAC secret key not found",
      "Environment error. RBAC_SECRET_KEY not found",
      "Invalid id",
      "Payment intent not found",
      "Currency is required",
      "Currency not found",
      "Invalid id, id is required",
      "Invalid id. Got:",
      "Not Found entity with id:",
      "Query segment is required",
      "Query url is required",
      "Invalid orderToProductId",
      "Invalid messageId, messageId is required",
      "Invalid data",
      "Invalid data, data is required",
      "Invalid data, slug and payload are required",
      "Invalid data, should be array [{'id':'<string>','data':<any>},...]",
      "Invalid data, should be array [{'data':<any>},...]",
      "Invalid body",
      "Invalid notification method",
      "No uuid provided",
      "No notification.notification.method provided",
      "No notification.topic.slug provided",
      "No template variant provided",
      "Files are not supported",
      "Missing headers",
      /Provider .* is not allowed/i,
      "Email is required",
      "Payment intents to invoices not found",
      "Cloudpayments credentials not found",
      "Cloudpayments invoice id not found",
      "Channel not found",
      "Invalid data, slug and payload are required.",
      "Invalid data, data is required.",
      "Invalid id, id is required.",
      "Invalid messageId, messageId is required.",
      "Stripe secret key not found",
      "Orders to billing module payment intents not found",
      "Payment intents not found",
      "Payment intent is not succeeded",
      "Invalid file",
      "Invalid file type",
      "Invalid message or signature",
      "Invalid signature",
      "Multiple subjects to identities found",
      "Cannot delete last identity",
      "Account already exists",
      "Invalid date in message",
      "Multiple files are not allowed",
      "Missing one or more action parameters (route, method, type)",
      "Multiple identities found",
      "Could not update identity",
      "No salt found for this identity",
      "Passwords do not match",
      "No password provided",
      "Code is expired. Resend again.",
      "No code provided",
      "No method provided in 'action' quer",
      "No route provided in 'action' query",
      "No action provided in query",
      "Configuration error.",
      "No data.formId provided",
      "No productId provided",
      "Multiple billing module payment",
      "Invalid provider",
      "Invalid orderToProductId. Got",
      "Invalid id. Got: ",
    ],
  ],

  [
    401,
    [
      /invalid credentials/i,
      /unauthorized/i,
      /token required/i,
      /no session/i,
      "Authorization error",
      "No subject provided in the token",
    ],
  ],

  [
    403,
    [
      "Forbidden",
      "Authentication",
      "Permission",
      "Unauthorized",
      "Only order owner can update order",
      "Only identity owner can create identity.",
    ],
  ],

  [
    404,
    [
      "not found",
      "Not found",
      "Not found. Entity with id ",
      "Form not found",
      "Entity not found",
      /Entity with param  .* not found/i,
      "No inputs found",
      "Order already exists",
      "No topic found",
      "No form found",
      "No ecommerceModule provided",
      "No ecommerce module orders found",
      "No ecommerceModule.orders provided",
      "No data.productId provided",
      "No ecommerceModule.orders[number].id provided",
      "Multiple stores found. Pass 'data.storeId",
      "No email provided",
      "No stores found",
      "No inputs found for form with id",
      "No orderId provided",
      "No ordersToProducts provided",
      "Order is not in 'new' status",
      "No template found",
      "Order not found",
      "Order to product not found",
      "Orders to products not found",
      "No orders to products found",
      "No ecommerce module products found",
      "No ecommerce module attributes keys to attributes found",
      "No ecommerce module attributes keys found",
      "No ecommerce module attributes found",
      "No ecommerce module products to attributes found",
      "No stores to orders found",
      "No orders to billing module currencies found",
      "Products not found",
      "Billing currencies not found",
      "Orders to billing module currencies not found",
      "Billing module currencies not found",
      "No subjects to identities found",
      "No identities found",
      "No products to attributes found",
      "No attribute keys to attributes found",
      "No order found",
      "No entity found",
      "No payment intents found",
      "No payment intents to invoices found",
      "No invoices found",
      "No updated order found",
      "Not found. No matching action for route:",
      "No ecommerce orders to billing module currencies found",
      "No billing module currency id found for order: ",
    ],
  ],

  [
    422,
    [
      "Expected string",
      "Invalid body['data']",
      "Unprocessable Entity",
      "Invalid type. Expected email, got:",
    ],
  ],

  [
    500,
    [
      "Configuration error",
      "Internal Server Error",
      "Internal server error",
      "Request not created",
      "JWT secret not provided",
    ],
  ],
]);
