import { ErrorPatternEntry } from "../type";

export const httpErrorPatterns: ErrorPatternEntry[] = [
  {
    status: 401,
    category: "Authentication error",
    patterns: [
      /invalid credentials/i,
      /unauthorized/i,
      /token required/i,
      /no session/i,
      /authorization error/i,
      /no subject provided in the token/i,
    ],
  },
  {
    status: 400,
    category: "Validation error",
    patterns: [
      /invalid request body/i,
      /validation error/i,
      /no id provided/i,
      /invalid url/i,
      /invalid (data|body)/i,
      /invalid data, (slug and payload|data) are required([.]|.)?/i,
      /invalid data, should be array/i,
      /invalid notification method/i,
      /missing headers/i,
      /invalid provider/i,
      /invalid ordertoproductid/i,
      /invalid messageid([.,]|, messageid is required)?/i,
      /invalid id([.,]|, id is required)?/i,
      /invalid type[.]? expected email, got:?/i,
      /expected string/i,
      /invalid body\['data'\]/i,
    ],
  },
  {
    status: 403,
    category: "Permission error",
    patterns: [
      /forbidden/i,
      /permission/i,
      /authentication/i,
      /only order owner can update order/i,
      /only identity owner can create identity/i,
    ],
  },
  // Not Found — no entity, no data, not found
  {
    status: 404,
    category: "Not Found error",
    patterns: [
      /not found/i,
      /entity not found/i,
      /form not found/i,
      /entity with param .* not found/i,
      /no (inputs|uuid|productid|orderid|email|stores|template|attributes?|products?|orders?|subjects to identities|attribute keys to attributes|orders to products|ecommerce orders to billing module currencies|billing module currency id) found/i,
      /order already exists/i,
      /order is not in 'new' status/i,
      /not found[.]? entity with id/i,
      /not found[.]? no matching action for route:?/i,
      /no updated order found/i,
      /no payment intents found/i,
      /no invoices found/i,
      /no payment intents to invoices found/i,
      /no ecommerce(module)?( orders)?( products)?( attributes)?(?:.*) provided/i,
    ],
  },
  {
    status: 400,
    category: "Payment error",
    patterns: [
      /payment intent not found/i,
      /payment intents to invoices not found/i,
      /cloudpayments (credentials|invoice id) not found/i,
      /stripe secret key not found/i,
      /payment intent is not succeeded/i,
      /orders to billing module payment intents not found/i,
      /orders to billing module currencies not found/i,
      /billing currencies not found/i,
      /billing module currencies not found/i,
      /multiple billing module payment/i,
      /channel not found/i,
    ],
  },
  {
    status: 500,
    category: "Internal error",
    patterns: [
      /configuration error[.]?/i,
      /environment error[.,]? rbac_secret_key not found/i,
      /rbac_jwt_secret not set/i,
      /rbac_secret_key not set/i,
      /rbac_secret_key is not defined/i,
      /rbac_anonymous_jwt_refresh_token_lifetime_in_seconds not set/i,
      /rbac secret key not found/i,
      /internal server error/i,
      /request not created/i,
      /jwt secret not provided/i,
      /server error/i,
    ],
  },
];
