---
- name: Delete S3 bucket
  hosts: all
  become: yes
  vars:
    root_aws_access_key_id: "{{ ROOT_AWS_ACCESS_KEY_ID }}"
    root_aws_secret_access_key: "{{ ROOT_AWS_SECRET_ACCESS_KEY }}"
    project_name: "{{ PROJECT_NAME }}"
    aws_s3_bucket_name: "{{ AWS_S3_BUCKET_NAME }}"
  tasks:
    - name: Get ansible ansible_system_vendor
      set_fact:
        ansible_system_vendor: "{{ hostvars[inventory_hostname]['ansible_system_vendor'] }}"

    - name: If DigitalOcean
      block:
        - name: Install required Python packages
          pip:
            name: "{{ item }}"
            state: present
            virtualenv: /opt/venv
          loop:
            - boto
            - boto3
            - botocore
            - awscli
      when: ansible_system_vendor == "DigitalOcean"

    - name: If not DigitalOcean
      block:
        - name: Install required Python packages
          pip:
            name: "{{ item }}"
            state: present
            virtualenv: /opt/venv
          loop:
            - boto
            - boto3
            - botocore
            - awscli
      when: ansible_system_vendor != "DigitalOcean"

    - name: Delete S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ item }}"
        access_key: "{{ root_aws_access_key_id }}"
        secret_key: "{{ root_aws_secret_access_key }}"
        state: absent
        force: true
      ignore_errors: yes
      loop:
        - "{{ aws_s3_bucket_name }}"
        - "{{ aws_s3_bucket_name }}dev"

    - name: Delete S3 name file
      file:
        path: "/home/code/{{ item }}"
        state: absent
      loop:
        - "s3_bucket"
        - "s3_bucket_dev"
