---
- name: Fill AWS secrets in GitHub
  hosts: all
  become: yes
  vars:
    - github_token: "{{ GITHUB_TOKEN }}"
    - github_repository: "{{ GITHUB_REPOSITORY }}"
    - project_name: "{{ PROJECT_NAME }}"
    - aws_region: "{{ AWS_REGION }}"
    - aws_s3_bucket_name: "{{ AWS_S3_BUCKET_NAME }}"
    - environment_type: "{{ ENVIRONMENT_TYPE }}"
  tasks:
    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent

    - name: Set ENVIRONMENT_TYPE_PREFIX
      set_fact:
        ENVIRONMENT_TYPE_PREFIX: "{{ environment_type | default('') ~ '_' if environment_type else '' }}"

    - name: Create github-node-api directory
      file:
        path: "/home/code/github-node-api"
        state: directory

    - name: Fill github-node-api directory from local
      copy:
        src: "{{ playbook_dir }}/../github/github-node-api/{{ item }}"
        dest: "/home/code/github-node-api/{{ item }}"
      loop:
        - create_secret.js
        - package.json

    - name: Install dependencies
      shell:
        cmd: "npm install"
        chdir: "/home/code/github-node-api"

    - name: Get AWS_ACCESS_KEY_ID from dev.iam.env file
      shell:
        cmd: "echo $(cat /home/code/dev.iam.env | grep AWS_ACCESS_KEY_ID | cut -d '=' -f2)"
      register: dev_aws_access_key_id

    - name: Get dev AWS_SECRET_ACCESS_KEY from iam.env file
      shell:
        cmd: "echo $(cat /home/code/dev.iam.env | grep AWS_SECRET_ACCESS_KEY | cut -d '=' -f2)"
      register: dev_aws_secret_access_key

    - name: Get AWS_ACCESS_KEY_ID from iam.env file
      shell:
        cmd: "echo $(cat /home/code/iam.env | grep AWS_ACCESS_KEY_ID | cut -d '=' -f2)"
      register: aws_access_key_id

    - name: Get AWS_SECRET_ACCESS_KEY from iam.env file
      shell:
        cmd: "echo $(cat /home/code/iam.env | grep AWS_SECRET_ACCESS_KEY | cut -d '=' -f2)"
      register: aws_secret_access_key

    - name: Set secrets to GitHub
      no_log: true
      shell:
        cmd: "node ./create_secret.js {{ github_token }} {{ github_repository }} {{ item.secret_name }} {{ item.secret_content }} {{ item.secret_scope }}"
        chdir: "/home/code/github-node-api"
      loop:
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_ACCESS_KEY_ID' }}",
            secret_content: "{{ dev_aws_access_key_id.stdout }}",
            secret_scope: codespaces,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_SECRET_ACCESS_KEY' }}",
            secret_content: "{{ dev_aws_secret_access_key.stdout }}",
            secret_scope: codespaces,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_S3_BUCKET' }}",
            secret_content: "{{ aws_s3_bucket_name }}dev",
            secret_scope: codespaces,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_REGION' }}",
            secret_content: "{{ aws_region }}",
            secret_scope: codespaces,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_S3_ENDPOINT' }}",
            secret_content: "https://s3.amazonaws.com/{{ aws_s3_bucket_name }}dev",
            secret_scope: codespaces,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_S3_BUCKET' }}",
            secret_content: "{{ aws_s3_bucket_name }}",
            secret_scope: actions,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_S3_ENDPOINT' }}",
            secret_content: "https://s3.amazonaws.com/{{ aws_s3_bucket_name }}",
            secret_scope: actions,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_ACCESS_KEY_ID' }}",
            secret_content: "{{ aws_access_key_id.stdout }}",
            secret_scope: actions,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'AWS_SECRET_ACCESS_KEY' }}",
            secret_content: "{{ aws_secret_access_key.stdout }}",
            secret_scope: actions,
          }

    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent
