---
- name: Create certbot
  hosts: all
  become: yes
  vars:
    - service_name: "{{ SERVICE_NAME }}"
  tasks:
    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.certbot.yaml.j2
        dest: /home/code/docker-compose.certbot.yaml

    - name: Create certbot challenge directory
      file:
        path: /home/code/certbot/.well-known/acme-challenge
        state: directory
        mode: "0755"
        recurse: yes

    - name: Run certbot service
      shell: docker stack deploy --compose-file=/home/code/docker-compose.certbot.yaml certbot
