---
- name: Delete Sentry Project
  hosts: all
  become: yes
  vars:
    sentry_api_key: "{{ SENTRY_API_KEY }}"
    sentry_organization_slug: "{{ SENTRY_ORGANIZATION_SLUG }}"
    sentry_team_slug: "{{ SENTRY_TEAM_SLUG }}"
    project_name: "{{ PROJECT_NAME }}"
    service_name: "{{ SERVICE_NAME }}"
  tasks:
    - name: Delete sentry project
      uri:
        url: "https://sentry.io/api/0/projects/{{ sentry_organization_slug }}/{{ project_name }}_{{ service_name }}/"
        method: DELETE
        headers:
          Authorization: "Bearer {{ sentry_api_key }}"
        status_code: 204
      register: sentry_project
      ignore_errors: yes

    - name: Delete file with DSN keys
      file:
        path: "/home/code/{{ service_name }}_sentry_dsn.env"
        state: absent
