/**
 * BDD Suite: Database credentials written by the bootstrap scripts
 * Given apps/db/create_env.sh and apps/api/create_env.sh run in a checkout
 * When the API environment is generated from the database environment
 * Then the API receives the application role, which is a different role with a
 *      different password from the PostgreSQL superuser, and a database
 *      environment written before that role existed keeps the API on the
 *      superuser it was initialized with
 */
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";

const repositoryRoot = process.cwd();
const scratch = mkdtempSync(path.join(os.tmpdir(), "sps-create-env-"));
const repositoryName = "role-check";

afterAll(() => {
  rmSync(scratch, { recursive: true, force: true });
});

interface IShellResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

/**
 * Runs a bash snippet in a checkout directory. Output is redirected to files
 * rather than captured through pipes, because bun 1.3.6 loses piped child
 * output for a test file that lives in a subdirectory. The environment is
 * reduced to PATH and HOME so hosted-workspace variables cannot change the
 * scripts' branches, and the administrator password is supplied so the API
 * script does not generate and print one.
 */
function runShell(cwd: string, script: string): IShellResult {
  const stdoutPath = path.join(scratch, "stdout");
  const stderrPath = path.join(scratch, "stderr");

  const result = spawnSync(
    "bash",
    ["-c", `{\n${script}\n} > "${stdoutPath}" 2> "${stderrPath}"`],
    {
      cwd,
      env: {
        PATH: process.env["PATH"],
        HOME: scratch,
        RBAC_SUBJECT_IDENTITY_PASSWORD: "bootstrap-admin-password",
      },
      stdio: "ignore",
    },
  );

  return {
    status: result.status,
    stdout: readFileSync(stdoutPath, "utf8"),
    stderr: readFileSync(stderrPath, "utf8"),
  };
}

/**
 * Lays out the directories the scripts expect relative to each other: the
 * deployer helpers they source, the two app directories and the Redis
 * environment the API script reads. The checkout is a Git repository whose
 * origin remote names the project, as apps/db/create_env.sh derives its names
 * from it.
 */
function createCheckout(name: string): string {
  const checkout = path.join(scratch, name);

  for (const directory of [
    "tools/deployer",
    "apps/db",
    "apps/api",
    "apps/redis",
  ]) {
    mkdirSync(path.join(checkout, directory), { recursive: true });
  }

  for (const file of [
    "tools/deployer/generate_secret.sh",
    "tools/deployer/get_env.sh",
    "apps/db/create_env.sh",
    "apps/api/create_env.sh",
  ]) {
    copyFileSync(path.join(repositoryRoot, file), path.join(checkout, file));
  }

  writeFileSync(
    path.join(checkout, "apps/redis/.env"),
    "REDIS_PORT=6379\nREDIS_PASSWORD=redis-password\n",
  );

  const repository = runShell(
    checkout,
    `git init --quiet && git remote add origin "https://github.com/example/${repositoryName}.git"`,
  );

  expect(repository.status).toBe(0);

  return checkout;
}

function readEnv(file: string): Record<string, string> {
  const values: Record<string, string> = {};

  for (const line of readFileSync(file, "utf8").split("\n")) {
    const separator = line.indexOf("=");

    if (separator > 0 && !line.startsWith("#")) {
      values[line.slice(0, separator)] = line.slice(separator + 1);
    }
  }

  return values;
}

function runCreateEnv(checkout: string, app: "db" | "api"): IShellResult {
  const result = runShell(
    path.join(checkout, "apps", app),
    "bash create_env.sh",
  );

  expect(result.status).toBe(0);

  return result;
}

describe("a fresh bootstrap", () => {
  let apiRun: IShellResult;
  let database: Record<string, string>;
  let api: Record<string, string>;

  beforeAll(() => {
    const checkout = createCheckout("fresh");

    runCreateEnv(checkout, "db");
    apiRun = runCreateEnv(checkout, "api");

    database = readEnv(path.join(checkout, "apps/db/.env"));
    api = readEnv(path.join(checkout, "apps/api/.env"));
  });

  /**
   * BDD Scenario: The API connects as the application role
   * Given apps/db/.env generated by the database bootstrap
   * When the API bootstrap writes apps/api/.env
   * Then its database user and password are the application role's, not the
   *      superuser's
   */
  test("gives the API the application role instead of the superuser", () => {
    expect(api["DATABASE_USERNAME"]).toBe(database["DATABASE_USERNAME"]);
    expect(api["DATABASE_PASSWORD"]).toBe(database["DATABASE_PASSWORD"]);
    expect(api["DATABASE_USERNAME"]).not.toBe(database["POSTGRES_USER"]);
    expect(api["DATABASE_PASSWORD"]).not.toBe(database["POSTGRES_PASSWORD"]);
    expect(apiRun.stdout).not.toContain("superuser");
  });

  /**
   * BDD Scenario: Two roles with their own passwords
   * Given a fresh database bootstrap
   * When apps/db/.env is written
   * Then the superuser is postgres, the application role takes the project
   *      name the API used before, and each has its own 64-character password
   */
  test("names the superuser and the application role apart with separate secrets", () => {
    expect(database["POSTGRES_USER"]).toBe("postgres");
    expect(database["DATABASE_USERNAME"]).toBe(repositoryName);
    expect(database["POSTGRES_DB"]).toBe(repositoryName);
    expect(database["POSTGRES_PASSWORD"]).toMatch(/^[0-9a-f]{64}$/);
    expect(database["DATABASE_PASSWORD"]).toMatch(/^[0-9a-f]{64}$/);
    expect(database["DATABASE_PASSWORD"]).not.toBe(
      database["POSTGRES_PASSWORD"],
    );
  });

  /**
   * BDD Scenario: The connection target is unchanged
   * Given a fresh bootstrap
   * When the API environment is written
   * Then it points at the same database name and port the database uses
   */
  test("keeps the API on the database name and port of apps/db", () => {
    expect(api["DATABASE_NAME"]).toBe(database["POSTGRES_DB"]);
    expect(api["DATABASE_PORT"]).toBe(database["POSTGRES_PORT"]);
    expect(api["DATABASE_HOST"]).toBe("localhost");
  });
});

describe("a checkout bootstrapped before the application role", () => {
  /**
   * BDD Scenario: A database environment without the application role
   * Given apps/db/.env holds only the superuser, as it did before the role
   *      existed, and its data directory has no other role
   * When only apps/api/.env is regenerated
   * Then the API keeps the superuser credentials and the script says so
   */
  test("keeps the API on the superuser and says so", () => {
    const checkout = createCheckout("legacy");
    const superuserPassword = "a".repeat(64);

    writeFileSync(
      path.join(checkout, "apps/db/.env"),
      [
        `COMPOSE_PROJECT_NAME=${repositoryName}`,
        `POSTGRES_DB=${repositoryName}`,
        `POSTGRES_USER=${repositoryName}`,
        `POSTGRES_PASSWORD=${superuserPassword}`,
        "POSTGRES_PORT=5433",
        "",
      ].join("\n"),
    );

    const apiRun = runCreateEnv(checkout, "api");
    const api = readEnv(path.join(checkout, "apps/api/.env"));

    expect(api["DATABASE_USERNAME"]).toBe(repositoryName);
    expect(api["DATABASE_PASSWORD"]).toBe(superuserPassword);
    expect(api["DATABASE_PORT"]).toBe("5433");
    expect(apiRun.stdout).toContain("connects as the PostgreSQL superuser");
  });
});
