---
- name: Create llm
  hosts: all
  become: yes
  vars:
    service_name: "{{ SERVICE_NAME }}"
    portainer_username: "{{ PORTAINER_USERNAME }}"
    portainer_password: "{{ PORTAINER_PASSWORD }}"
    portainer_url: "{{ PORTAINER_URL }}"
  tasks:
    - name: Create ollama_data directory
      file:
        path: /home/code/ollama_data
        state: directory

    - name: Copy Ollama model reconciler
      copy:
        src: ../../../apps/llm/ollama-init.sh
        dest: /home/code/ollama-init.sh
        mode: "0755"

    - name: Copy set-portainer-webhook.js
      copy:
        src: ../portainer/set-portainer-webhook.js
        dest: /home/code/set-portainer-webhook.js

    - name: Get registry_id from file
      shell: cat /home/code/docker_hub_registry_id
      register: cmd_docker_hub_registry_id

    - name: Create llm.env file
      ansible.builtin.template:
        src: llm.env.j2
        dest: "/home/code/{{ service_name }}.env"

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.llm.yaml.j2
        dest: /home/code/docker-compose.llm.yaml

    - name: Run llm service
      shell: docker stack deploy --with-registry-auth --compose-file=/home/code/docker-compose.llm.yaml {{ service_name }}

    - name: Get llm service id
      shell:
        cmd: "docker service ls -f name={{ service_name }}_{{ service_name }} -q"
      register: cmd_llm_service_id

    - name: Run set-portainer-webhook.js
      shell:
        cmd: node /home/code/set-portainer-webhook.js "{{ cmd_llm_service_id.stdout_lines[0] }}" "{{ cmd_docker_hub_registry_id.stdout }}" "{{ portainer_url }}" "{{ portainer_username }}" "{{ portainer_password }}" "llm_webhook"
      register: cmd_set_llm_webhook

    - name: Copy webhook info file
      fetch:
        src: /home/code/llm_webhook.json
        dest: "./"
        flat: yes

    - name: Delete artifacts
      file:
        path: "/home/code/{{ item }}"
        state: absent
      loop:
        - "set-portainer-webhook.js"
