import {
  AUDIO_TRANSCRIPTION_DEFAULT_MODEL,
  AUDIO_TRANSCRIPTION_LEGACY_METADATA_KEY,
  AUDIO_TRANSCRIPTION_MAX_BYTES,
} from "./audio-transcription";

export const TELEGRAM_VOICE_TRANSCRIPTION_METADATA_KEY =
  AUDIO_TRANSCRIPTION_LEGACY_METADATA_KEY;
export const TELEGRAM_VOICE_TRANSCRIPTION_ACTION_TYPE =
  "telegram_voice_transcription_completed";
export const TELEGRAM_VOICE_TRANSCRIPTION_DEFAULT_MODEL =
  AUDIO_TRANSCRIPTION_DEFAULT_MODEL;
export const TELEGRAM_VOICE_TRANSCRIPTION_MAX_BYTES =
  AUDIO_TRANSCRIPTION_MAX_BYTES;
