#!/bin/bash
. ./get_environment_type.sh

get_environment_type $2

./create_inventory.sh

. ./get_env.sh

DOMAIN=$(get_env "$BASH_SOURCE" "DOMAIN")

SERVICE_NAME=$(get_env "$BASH_SOURCE" "LLM_SERVICE_NAME")

if [ -z "$SERVICE_NAME" ]; then
    SERVICE_NAME=llm
fi

PORTAINER_USERNAME=$(get_env "$BASH_SOURCE" "PORTAINER_USERNAME")
PORTAINER_PASSWORD=$(get_env "$BASH_SOURCE" "PORTAINER_PASSWORD")
PORTAINER_SERVICE_SUBDOMAIN=$(get_env "$BASH_SOURCE" "PORTAINER_SERVICE_SUBDOMAIN")

DOCKER_HUB_URL=$(get_env "$BASH_SOURCE" "DOCKER_HUB_URL")
DOCKER_HUB_SERVICE_REPOSITORY=$(get_env "$BASH_SOURCE" "LLM_SERVICE_DOCKER_HUB_REPOSITORY_NAME")

if [ -z "$DOCKER_HUB_SERVICE_REPOSITORY" ]; then
    DOCKER_HUB_SERVICE_REPOSITORY=$(get_env "$BASH_SOURCE" "HOST_SERVICE_DOCKER_HUB_REPOSITORY_NAME")
fi

OPENAI_API_KEY=$(get_env "$BASH_SOURCE" "OPENAI_API_KEY")
OPEN_AI_API_KEY=$(get_env "$BASH_SOURCE" "OPEN_AI_API_KEY")
ANTHROPIC_API_KEY=$(get_env "$BASH_SOURCE" "ANTHROPIC_API_KEY")
HF_TOKEN=$(get_env "$BASH_SOURCE" "HF_TOKEN")
OLLAMA_MODEL_IDS=$(get_env "$BASH_SOURCE" "OLLAMA_MODEL_IDS")
LLM_PRELOAD_MODEL_IDS=$(get_env "$BASH_SOURCE" "LLM_PRELOAD_MODEL_IDS")
LLM_MAX_LOADED_HF_MODELS=$(get_env "$BASH_SOURCE" "LLM_MAX_LOADED_HF_MODELS")
WHISPER_MODEL=$(get_env "$BASH_SOURCE" "WHISPER_MODEL")
WHISPER_DEVICE=$(get_env "$BASH_SOURCE" "WHISPER_DEVICE")
WHISPER_COMPUTE_TYPE=$(get_env "$BASH_SOURCE" "WHISPER_COMPUTE_TYPE")

GITHUB_TOKEN=$(get_env "$BASH_SOURCE" "GITHUB_TOKEN")
GITHUB_REPOSITORY=$(get_env "$BASH_SOURCE" "GITHUB_REPOSITORY")

PORTAINER_URL=$PORTAINER_SERVICE_SUBDOMAIN.$DOMAIN

if [ -z "$DOCKER_HUB_SERVICE_REPOSITORY" ]
then
    echo "No docker hub repository name for service $SERVICE_NAME"
    exit 0
fi

if [ "$1" != "down" ]
then
    ./pull_docker_image.sh "$DOCKER_HUB_URL/$DOCKER_HUB_SERVICE_REPOSITORY" "$ENVIRONMENT_TYPE" && \
    ./pull_docker_image.sh "ollama/ollama:latest" "$ENVIRONMENT_TYPE" && \
    ansible-playbook \
        ./llm/create_llm.yaml \
        -e "SERVICE_NAME=$SERVICE_NAME \
            PORTAINER_URL=$PORTAINER_URL \
            PORTAINER_USERNAME=$PORTAINER_USERNAME \
            PORTAINER_PASSWORD=$PORTAINER_PASSWORD \
            DOCKER_HUB_URL=$DOCKER_HUB_URL \
            DOCKER_HUB_SERVICE_REPOSITORY=$DOCKER_HUB_SERVICE_REPOSITORY \
            OPENAI_API_KEY=$OPENAI_API_KEY \
            OPEN_AI_API_KEY=$OPEN_AI_API_KEY \
            ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
            HF_TOKEN=$HF_TOKEN \
            OLLAMA_MODEL_IDS=$OLLAMA_MODEL_IDS \
            LLM_PRELOAD_MODEL_IDS=$LLM_PRELOAD_MODEL_IDS \
            LLM_MAX_LOADED_HF_MODELS=$LLM_MAX_LOADED_HF_MODELS \
            WHISPER_MODEL=$WHISPER_MODEL \
            WHISPER_DEVICE=$WHISPER_DEVICE \
            WHISPER_COMPUTE_TYPE=$WHISPER_COMPUTE_TYPE \
            ENVIRONMENT_TYPE=$ENVIRONMENT_TYPE" && \
    ansible-playbook \
        ./llm/fill_github.yaml \
        -e "GITHUB_TOKEN=$GITHUB_TOKEN \
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            PORTAINER_URL=$PORTAINER_URL \
            ENVIRONMENT_TYPE=$ENVIRONMENT_TYPE"
else
    ansible-playbook \
        ./llm/clear_github.yaml \
        -e "GITHUB_TOKEN=$GITHUB_TOKEN \
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            ENVIRONMENT_TYPE=$ENVIRONMENT_TYPE" && \
    ansible-playbook \
        ./llm/delete_llm.yaml \
        -e "SERVICE_NAME=$SERVICE_NAME"
fi
