#!/bin/bash
. ./get_environment_type.sh

get_environment_type $2

./create_inventory.sh

. ./get_env.sh

DOMAIN=$(get_env "$BASH_SOURCE" "DOMAIN")

API_SERVICE_SUBDOMAIN=$(get_env "$BASH_SOURCE" "API_SERVICE_SUBDOMAIN")

SERVICE_NAME=$(get_env "$BASH_SOURCE" "MCP_SERVICE_NAME")
SERVICE_SUBDOMAIN=$(get_env "$BASH_SOURCE" "MCP_SERVICE_SUBDOMAIN")

if [ -z "$SERVICE_NAME" ]; then
    SERVICE_NAME=mcp
fi

if [ -z "$SERVICE_SUBDOMAIN" ]; then
    SERVICE_SUBDOMAIN=mcp
fi

PORTAINER_USERNAME=$(get_env "$BASH_SOURCE" "PORTAINER_USERNAME")
PORTAINER_PASSWORD=$(get_env "$BASH_SOURCE" "PORTAINER_PASSWORD")
PORTAINER_SERVICE_SUBDOMAIN=$(get_env "$BASH_SOURCE" "PORTAINER_SERVICE_SUBDOMAIN")

RBAC_JWT_SECRET=$(get_env "$BASH_SOURCE" "RBAC_JWT_SECRET")
RBAC_SECRET_KEY=$(get_env "$BASH_SOURCE" "RBAC_SECRET_KEY")

REDIS_PASSWORD=$(get_env "$BASH_SOURCE" "REDIS_PASSWORD")
REDIS_PORT=$(get_env "$BASH_SOURCE" "REDIS_PORT")

MCP_ALLOW_RBAC_SECRET_FALLBACK=$(get_env "$BASH_SOURCE" "MCP_ALLOW_RBAC_SECRET_FALLBACK")
MCP_ALLOWED_ORIGINS=$(get_env "$BASH_SOURCE" "MCP_ALLOWED_ORIGINS")
MCP_OAUTH_JWT_SECRET=$(get_env "$BASH_SOURCE" "MCP_OAUTH_JWT_SECRET")
MCP_OAUTH_AUTH_CODE_TTL_SECONDS=$(get_env "$BASH_SOURCE" "MCP_OAUTH_AUTH_CODE_TTL_SECONDS")
MCP_OAUTH_ACCESS_TOKEN_TTL_SECONDS=$(get_env "$BASH_SOURCE" "MCP_OAUTH_ACCESS_TOKEN_TTL_SECONDS")
MCP_OAUTH_REFRESH_TOKEN_TTL_SECONDS=$(get_env "$BASH_SOURCE" "MCP_OAUTH_REFRESH_TOKEN_TTL_SECONDS")

DOCKER_HUB_URL=$(get_env "$BASH_SOURCE" "DOCKER_HUB_URL")
DOCKER_HUB_SERVICE_REPOSITORY=$(get_env "$BASH_SOURCE" "MCP_SERVICE_DOCKER_HUB_REPOSITORY_NAME")

if [ -z "$DOCKER_HUB_SERVICE_REPOSITORY" ]; then
    DOCKER_HUB_SERVICE_REPOSITORY=$(get_env "$BASH_SOURCE" "HOST_SERVICE_DOCKER_HUB_REPOSITORY_NAME")
fi

if [ -z "$DOCKER_HUB_SERVICE_REPOSITORY" ]; then
    DOCKER_HUB_SERVICE_REPOSITORY=$(get_env "$BASH_SOURCE" "API_SERVICE_DOCKER_HUB_REPOSITORY_NAME")
fi

GITHUB_TOKEN=$(get_env "$BASH_SOURCE" "GITHUB_TOKEN")
GITHUB_REPOSITORY=$(get_env "$BASH_SOURCE" "GITHUB_REPOSITORY")

PORTAINER_URL=$PORTAINER_SERVICE_SUBDOMAIN.$DOMAIN

if [ -z "$API_SERVICE_SUBDOMAIN" ]
then
    API_SERVICE_URL=$DOMAIN
else
    API_SERVICE_URL=$API_SERVICE_SUBDOMAIN.$DOMAIN
fi

if [ -z "$SERVICE_SUBDOMAIN" ]
then
    SERVICE_A="@"
    SERVICE_URL=$DOMAIN
else
    SERVICE_A=$SERVICE_SUBDOMAIN
    SERVICE_URL=$SERVICE_SUBDOMAIN.$DOMAIN
fi

if [ -z "$DOCKER_HUB_SERVICE_REPOSITORY" ]
then
    echo "No docker hub repository name for service $SERVICE_NAME"
    exit 0
fi

if [ "$1" != "down" ]
then
    ./domain.sh present $SERVICE_URL $SERVICE_A && \
    ansible-playbook \
        ./mcp/create_mcp.yaml \
        -e "SERVICE_NAME=$SERVICE_NAME \
            PORTAINER_URL=$PORTAINER_URL \
            PORTAINER_USERNAME=$PORTAINER_USERNAME \
            PORTAINER_PASSWORD=$PORTAINER_PASSWORD \
            DOCKER_HUB_URL=$DOCKER_HUB_URL \
            DOCKER_HUB_SERVICE_REPOSITORY=$DOCKER_HUB_SERVICE_REPOSITORY \
            API_SERVICE_URL=$API_SERVICE_URL \
            RBAC_JWT_SECRET=$RBAC_JWT_SECRET \
            RBAC_SECRET_KEY=$RBAC_SECRET_KEY \
            REDIS_PASSWORD=$REDIS_PASSWORD \
            REDIS_PORT=$REDIS_PORT \
            MCP_ALLOW_RBAC_SECRET_FALLBACK=$MCP_ALLOW_RBAC_SECRET_FALLBACK \
            MCP_ALLOWED_ORIGINS=$MCP_ALLOWED_ORIGINS \
            MCP_OAUTH_JWT_SECRET=$MCP_OAUTH_JWT_SECRET \
            MCP_OAUTH_AUTH_CODE_TTL_SECONDS=$MCP_OAUTH_AUTH_CODE_TTL_SECONDS \
            MCP_OAUTH_ACCESS_TOKEN_TTL_SECONDS=$MCP_OAUTH_ACCESS_TOKEN_TTL_SECONDS \
            MCP_OAUTH_REFRESH_TOKEN_TTL_SECONDS=$MCP_OAUTH_REFRESH_TOKEN_TTL_SECONDS \
            SERVICE_URL=$SERVICE_URL \
            ENVIRONMENT_TYPE=$ENVIRONMENT_TYPE" && \
    ansible-playbook \
        ./mcp/fill_github.yaml \
        -e "GITHUB_TOKEN=$GITHUB_TOKEN \
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            PORTAINER_URL=$PORTAINER_URL \
            SERVICE_URL=$SERVICE_URL \
            ENVIRONMENT_TYPE=$ENVIRONMENT_TYPE"
else
    ansible-playbook \
        ./mcp/clear_github.yaml \
        -e "GITHUB_TOKEN=$GITHUB_TOKEN \
            GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            ENVIRONMENT_TYPE=$ENVIRONMENT_TYPE" && \
    ansible-playbook \
        ./mcp/delete_mcp.yaml \
        -e "SERVICE_NAME=$SERVICE_NAME" && \
    ./domain.sh down $SERVICE_URL $SERVICE_A
fi
