version: "3.7"

services:
  redis:
    extends:
      file: ./docker-compose.redis.yaml
      service: redis
    networks:
      - redis_network

networks:
  redis_network:
    external: false
    name: ${COMPOSE_PROJECT_NAME}_redis_network
