---
- name: Create host
  hosts: all
  become: yes
  vars:
    service_name: "{{ SERVICE_NAME }}"
    portainer_username: "{{ PORTAINER_USERNAME }}"
    portainer_password: "{{ PORTAINER_PASSWORD }}"
    portainer_url: "{{ PORTAINER_URL }}"
  tasks:
    - name: Read iam.env and set AWS_ACCESS_KEY_ID
      shell: grep "^AWS_ACCESS_KEY_ID=" /home/code/iam.env | cut -d '=' -f2
      register: aws_access_key_id

    - name: Read iam.env and set AWS_SECRET_ACCESS_KEY
      shell: grep "^AWS_SECRET_ACCESS_KEY=" /home/code/iam.env | cut -d '=' -f2
      register: aws_secret_access_key

    - name: Copy set-portainer-webhook.js
      copy:
        src: ../portainer/set-portainer-webhook.js
        dest: /home/code/set-portainer-webhook.js

    - name: Get registry_id from file
      shell: cat /home/code/docker_hub_registry_id
      register: cmd_docker_hub_registry_id

    - name: Create host.env.local file
      ansible.builtin.template:
        src: host.env.local.j2
        dest: /home/code/host.env.local
      vars:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id.stdout }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key.stdout }}"

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.host.yaml.j2
        dest: /home/code/docker-compose.host.yaml

    - name: Run host service
      shell: docker stack deploy --with-registry-auth --compose-file=/home/code/docker-compose.host.yaml host

    - name: Get host service id
      shell:
        cmd: "docker service ls -f name=host_host -q"
      register: cmd_host_service_id

    - name: Run set-portainer-webhook.js
      shell:
        cmd: node /home/code/set-portainer-webhook.js "{{ cmd_host_service_id.stdout_lines[0] }}" "{{ cmd_docker_hub_registry_id.stdout }}" "{{ portainer_url }}" "{{ portainer_username }}" "{{ portainer_password }}" "host_webhook"
      register: cmd_set_host_webhook

    # - debug:
    #     msg: "{{ cmd_set_host_webhook }}"

    - name: Copy webhook info file
      fetch:
        src: /home/code/host_webhook.json
        dest: "./"
        flat: yes

    - name: Delete artifacts
      file:
        path: "/home/code/{{ item }}"
        state: absent
      loop:
        - "set-portainer-webhook.js"
