---
- name: Fill host secrets in GitHub
  hosts: all
  become: yes
  vars:
    - github_token: "{{ GITHUB_TOKEN }}"
    - github_repository: "{{ GITHUB_REPOSITORY }}"
    - portainer_url: "{{ PORTAINER_URL }}"
    - service_url: "{{ SERVICE_URL }}"
    - environment_type: "{{ ENVIRONMENT_TYPE }}"
    - api_service_url: "{{ API_SERVICE_URL }}"
  tasks:
    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent

    - name: Set ENVIRONMENT_TYPE_PREFIX
      set_fact:
        ENVIRONMENT_TYPE_PREFIX: "{{ environment_type | default('') ~ '_' if environment_type else '' }}"

    - name: Create github-node-api directory
      file:
        path: "/home/code/github-node-api"
        state: directory

    - name: Fill github-node-api directory from local
      copy:
        src: "{{ playbook_dir }}/../github/github-node-api/{{ item }}"
        dest: "/home/code/github-node-api/{{ item }}"
      loop:
        - create_secret.js
        - package.json

    - name: Install dependencies
      shell:
        cmd: "npm install"
        chdir: "/home/code/github-node-api"

    - name: Get Portainer host webhook token
      shell:
        cmd: "cat /home/code/host_webhook_token"
      register: host_webhook_token

    - name: Set secrets to GitHub
      no_log: true
      shell:
        cmd: "node ./create_secret.js {{ github_token }} {{ github_repository }} {{ item.secret_name }} {{ item.secret_content }} {{ item.secret_scope }}"
        chdir: "/home/code/github-node-api"
      loop:
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'PORTAINER_HOST_UPDATE_URL' }}",
            secret_content: "https://{{ portainer_url }}/api/webhooks/{{ host_webhook_token.stdout }}",
            secret_scope: actions,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'NEXT_PUBLIC_HOST_SERVICE_URL' }}",
            secret_content: "https://{{ service_url }}",
            secret_scope: actions,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'NEXT_PUBLIC_API_SERVICE_URL' }}",
            secret_content: "https://{{ api_service_url }}",
            secret_scope: actions,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'API_SERVICE_URL' }}",
            secret_content: "http://api:4000",
            secret_scope: actions,
          }
        - {
            secret_name: "{{ ENVIRONMENT_TYPE_PREFIX ~ 'NEXT_PUBLIC_API_SERVICE_WS_URL' }}",
            secret_content: "wss://{{ api_service_url }}",
            secret_scope: actions,
          }

    - name: Delete artifacts
      file:
        path: /home/code/github-node-api/
        state: absent
