IdParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/id.yaml"

LimitParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/limit.yaml"

OffsetParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/offset.yaml"

OrderByParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/order-by.yaml"

FiltersParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/filters.yaml"
