IdParam:
  name: id
  in: path
  required: true
  description: Resource ID
  schema:
    type: string
    format: uuid

PageParam:
  name: page
  in: query
  required: false
  description: Page number for pagination (0-indexed)
  schema:
    type: integer
    default: 0

LimitParam:
  name: limit
  in: query
  required: false
  description: Number of items per page
  schema:
    type: integer
    default: 20

SortParam:
  name: sort
  in: query
  required: false
  description: Sort field and direction (e.g., "createdAt:desc")
  schema:
    type: string

FilterParam:
  name: filters
  in: query
  required: false
  description: Filter parameters as JSON
  schema:
    type: string
