IdParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/id.yaml#/Id"

LimitParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/limit.yaml#/Limit"

OffsetParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/offset.yaml#/Offset"

OrderByParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/order-by.yaml#/OrderBy"

FiltersParam:
  $ref: "../../../libs/shared/backend/api/src/lib/query-builder/filters.yaml#/Filters"
