name: Create frontend and backend release

on:
  release:
    types:
      - released
      - prereleased

jobs:
  docker-image:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      TAG: ${{ github.event.release.tag_name }}
      PRERELEASE: ${{ github.event.release.prerelease }}

  update-api:
    uses: ./.github/workflows/api.yml
    secrets: inherit
    needs:
      - docker-image
    with:
      TAG: ${{ github.event.release.tag_name }}
      PRERELEASE: ${{ github.event.release.prerelease }}

  update-host:
    uses: ./.github/workflows/host.yml
    secrets: inherit
    needs:
      - docker-image
      - update-api
    with:
      TAG: ${{ github.event.release.tag_name }}
      PRERELEASE: ${{ github.event.release.prerelease }}

  update-telegram:
    uses: ./.github/workflows/telegram.yml
    secrets: inherit
    needs:
      - docker-image
      - update-api
    with:
      TAG: ${{ github.event.release.tag_name }}
      PRERELEASE: ${{ github.event.release.prerelease }}
