name: Update frontend

on:
  pull_request:
    types: [closed]
    branches:
      - update-frontend

jobs:
  docker-image:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      TAG: ${{ github.sha }}
      PRERELEASE: false

  update-host:
    uses: ./.github/workflows/host.yml
    secrets: inherit
    needs:
      - docker-image
    with:
      SLEEP_TIME: 0
      TAG: ${{ github.sha }}
      PRERELEASE: false
