---
- name: Create Portainer user
  hosts: all
  become: yes
  vars:
    portainer_username: "{{ PORTAINER_USERNAME }}"
    portainer_password: "{{ PORTAINER_PASSWORD }}"
    service_url: "{{ SERVICE_URL }}"
  tasks:
    - name: Create Portainer user request
      retries: 10
      delay: 15
      register: result
      until: result.status == 200 or result.status == 409
      uri:
        url: "https://{{ service_url }}/api/users/admin/init"
        status_code: 200,409
        method: POST
        body:
          Username: "{{ portainer_username }}"
          Password: "{{ portainer_password }}"
        body_format: json
        headers:
          Content-Type: "application/json"
