---
- name: Delete Postgres
  hosts: all
  become: yes
  tasks:
    - name: Remove Postgres stack
      shell: docker stack rm postgres
      register: result
      failed_when: result.rc != 0
      ignore_errors: false

    - name: Debug result of removing Postgres stack
      debug:
        var: result

    - name: Ensure Postgres stack is removed
      shell: docker stack ls | grep postgres
      register: check_postgres
      failed_when: check_postgres.rc == 0
      ignore_errors: true

    - name: Remove docker-compose file
      file:
        path: /home/code/docker-compose.postgres.yaml
        state: absent

    # - name: Delete postgres_data directory
    #   file:
    #     path: /home/code/postgres_data
    #     state: absent
