---
- name: Delete Postgres
  hosts: all
  become: yes
  tasks:
    - name: Delete Postgres service
      shell: docker compose -f /home/code/docker-compose.postgres.yaml down

    - name: Copy docker-compose file
      file:
        path: /home/code/docker-compose.postgres.yaml
        state: absent

    # - name: Delete postgres_data directory
    #   file:
    #     path: /home/code/postgres_data
    #     state: absent
